-- GTAV/update/x64/dlcpack/
--[[ 	DLC LIST
ar = mpairraces
apa = mpapartment
gr = mpgunrunning
hei = mpheist
bkr = mpbiker
ex = mpexecutive
impexp = mpimportexport (CEO vehicle missions
]]--

Citizen.CreateThread(function()
	LoadMpDlcMaps()
	EnableMpDlcMaps(true)
	-- Killhouse
		RequestIpl("killhouse")
		RequestIpl("killhouse_target")
		RequestIpl("hei_po1_07_long_0")
		RequestIpl("hei_po1_07_strm_0")
		RequestIpl("hei_po1_07_strm_1")
		RequestIpl("hei_po1_04")
	-- Comico
		--[[RequestIpl("comico")
		RequestIpl("hei_dt1_19_critical_0")
		RequestIpl("hei_dt1_19_strm_0")
		RequestIpl("hei_dt1_26_strm_0")
		RequestIpl("hei_dt1_rd1_critical_1")
		RequestIpl("hei_dt1_rd1_long_1")
		RequestIpl("hei_dt1_rd1_strm_5")
		RequestIpl("hei_dt1_rd1_strm_6")
		RequestIpl("hei_dt1_rd1_strm_7")]]--
    -- North Point Trim Track
        RequestIpl("trimtrack")
    -- Terrain de Foot (non activé)
        --RequestIpl("football")
        --RequestIpl("hei_hw1_19_strm_0")
        --RequestIpl("hei_hw1_rd_strm_6")
	-- Gouvernement
		RequestIpl("observatory")
		RequestIpl("apa_ch2_02_critical_0")
		RequestIpl("apa_ch2_02_long_0")
		RequestIpl("apa_ch2_02_strm_2")
		RequestIpl("apa_ch2_02_strm_3")
		RequestIpl("apa_ch2_02_strm_5")
    -- Base Militaire Zancudo
        RequestIpl("zancudo_base")
        RequestIpl("cs3_07_mpgates") -- portes
        RequestIpl("hei_cs3_07_strm_0") -- cargen ->
        RequestIpl("hei_cs3_07_strm_1")
        RequestIpl("hei_cs3_07_strm_4")
        RequestIpl("hei_cs3_07_strm_5")
    -- Prison
        RequestIpl("lr_cs6_04_strm_0")
        RequestIpl("lr_cs6_04_strm_3")
        RequestIpl("lr_cs6_04_strm_4")
        RequestIpl("lr_cs6_04_strm_5")
    -- Circuit Hippodrome
		RequestIpl("stock_circuit")
    -- Stock Car: 1 destructible / 2 indestrucible / 3 full
	 	--RequestIpl("stock_obstacle_1")
		--RequestIpl("stock_obstacle_2")
		--RequestIpl("stock_obstacle_3")
    -- Weazel News + Life Invader
        RequestIpl("weazel")
        RequestIpl("v_int_9")
    -- Parking3
        RequestIpl("hei_dt1_06_strm_0")
        RequestIpl("parking3")
	-- Benny's - Extérieur
		RequestIpl("bennys")
		RequestIpl("lr_sc1_02_long_0")
		RequestIpl("lr_sc1_02_strm_0")
		RequestIpl("lr_sc1_rd_long_0")
		RequestIpl("lr_sc1_rd_strm_1")
	-- Concessionnaire - Extérieur
	   	RequestIpl("concess")
		RequestIpl("shr_int")
	   	RequestIpl("hei_dt1_22_strm_0")
		RequestIpl("hei_dt1_rd1_strm_0")
		RequestIpl("hei_dt1_rd1_strm_1")
        RequestIpl("downtown_construction_site")
        RequestIpl("nodes431")
  	-- Yellow Jack - MMA Cage
       	RequestIpl("lr_cs4_14_strm_1")
		RequestIpl("lr_cs6_roads_long_0")
		RequestIpl("cage")
	-- Place des Enchères
        RequestIpl("enchere")
	   	RequestIpl("hei_bh1_20_strm_0")
    -- LSMC
        RequestIpl("lsmc")
	    RequestIpl("lr_sc1_rd_strm_3")
    -- Commissariat
        RequestIpl("hei_dt1_rd1_strm_5")
	--RequestIpl("sc1_rd_strm_3")
	-- Trevor: 1985.48, 3828.76, 32.5 (Trash or Tidy. Only choose one)
		RequestIpl("TrevorsTrailerTrash")
		--RequestIpl("trevorstrailertidy")
	-- Heist Jewel: -637.20 -239.16 38.1
		RequestIpl("post_hiest_unload")
	-- Max Renda: -585.82, -282.72, 35.45
		RequestIpl("refit_unload")
	-- Heist Union Depository: 2.69, -667.01, 16.13
		RequestIpl("FINBANK")
	-- Morgue: 239.75, -1360.64, 39.53
		RequestIpl("Coroner_Int_on")
		RequestIpl("coronertrash")
	-- Cluckin Bell: -146.38, 6161.5, 30.20
		RequestIpl("CS1_02_cf_onmission1")
		RequestIpl("CS1_02_cf_onmission2")
		RequestIpl("CS1_02_cf_onmission3")
		RequestIpl("CS1_02_cf_onmission4")
	-- Grapeseed's farm: 2447.9, 4973.4, 47.7
		RequestIpl("farm")
		RequestIpl("farmint")
		RequestIpl("farm_lod")
		RequestIpl("farm_props")
		RequestIpl("des_farmhouse")
	-- Grapeseed's burnt Farm
		--[[ RequestIpl("farm_burnt")
		RequestIpl("farm_burnt_lod")
		RequestIpl("farm_burnt_props")
		RequestIpl("farmint_cap")
		RequestIpl("farmint_cap_lod") ]]--
	-- FIB lobby: 105.45, -745.48, 44.75
		RemoveIpl("FIBlobbyfake")
		RequestIpl("FBI_colPLUG")
		RequestIpl("FBI_repair")
		RequestIpl("FIBlobby")
		RequestIpl("FBI_colPLUG")
		RequestIpl("FBI_repair")
	-- Garage in La Mesa (autoshop): 970.27453, -1826.56982, 31.11477
		RequestIpl("bkr_bi_id1_23_door")
	-- Hill Valley church - Grave: -282.46380000, 2835.84500000, 55.91446000
		RequestIpl("lr_cs6_08_grave_closed")
	-- Lost's trailer park: 49.49379000, 3744.47200000, 46.38629000
		RequestIpl("methtrailer_grp1")
	-- Raton Canyon river: -1652.83, 4445.28, 2.52
		RequestIpl("CanyonRvrShallow")
	-- Billboard: iFruit
		RequestIpl("FruitBB")
		RequestIpl("sc1_01_newbill")
		RequestIpl("hw1_02_newbill")
		RequestIpl("hw1_emissive_newbill")
		RequestIpl("sc1_14_newbill")
		RequestIpl("dt1_17_newbill")
	-- Lester's factory: 716.84, -962.05, 31.59
		RequestIpl("id2_14_during_door")
		RequestIpl("id2_14_during1")
	-- Life Invader lobby: -1047.9, -233, 39
		RequestIpl("facelobby")
	-- Tunnels
		RequestIpl("v_tunnel_hole")
	-- Carwash: 55.7, -1391.3, 30.5
		RequestIpl("Carwash_with_spinners")
	-- Stadium "Fame or Shame": -248.49, -2010.50, 34.57
		RequestIpl("sp1_10_real_interior")
		RequestIpl("sp1_10_real_interior_lod")
	-- House in Banham Canyon: -3086.42, 339.25, 6.37
		RequestIpl("ch1_02_open")
	-- Garage in La Mesa (autoshop): 970.27, -1826.56, 31.11
		RequestIpl("bkr_bi_id1_23_door")
	-- Hill Valley church - Grave: -282.46, 2835.84, 55.91
		RequestIpl("lr_cs6_08_grave_closed")
	-- Lost's trailer park: 49.49, 3744.47, 46.38
		RequestIpl("methtrailer_grp1")
	-- Lost safehouse: 984.15, -95.36, 74.50
		RemoveIpl("hei_bi_hw1_13_door")
		RequestIpl("bkr_bi_hw1_13_int")
	-- Zancudo Gates (GTAO like): -1600.30, 2806.73, 18.79
		--RequestIpl("CS3_07_MPGates")
	-- Pillbox hospital:
        RemoveIpl("rc12b_fixed")
		RequestIpl("rc12b_default")
		RemoveIpl("rc12b_destroyed")
		RemoveIpl("rc12b_hospitalinterior")
		RemoveIpl("rc12b_hospitalinterior_lod")
	-- Josh's house: -1117.16, 303.09, 66.52
		RequestIpl("bh1_47_joshhse_unburnt")
		RequestIpl("bh1_47_joshhse_unburnt_lod")
	-- Zancudo River (need streamed content): 86.81, 3191.64, 30.463
		RequestIpl("cs3_05_water_grp1")
		RequestIpl("cs3_05_water_grp1_lod")
		RequestIpl("cs3_05_water_grp2")
		RequestIpl("cs3_05_water_grp2_lod")
	-- Cassidy Creek (need streamed content): -425.67, 4433.40, 27.32
		RequestIpl("canyonriver01")
		RequestIpl("canyonriver01_lod")
	-- Graffitis
		RequestIpl("ch3_rd2_bishopschickengraffiti")	-- 1861.28, 2402.11, 58.53
		RequestIpl("cs5_04_mazebillboardgraffiti") 		-- 2697.32, 3162.18, 58.1
		RequestIpl("cs5_roads_ronoilgraffiti") 			-- 2119.12, 3058.21, 53.25
	-- Heist Carrier: 3082.31 -4717.11 15.26
		--[[ RequestIpl("hei_carrier")
		RequestIpl("hei_carrier_distantlights")
		RequestIpl("hei_Carrier_int1")
		RequestIpl("hei_Carrier_int2")
		RequestIpl("hei_Carrier_int3")
		RequestIpl("hei_Carrier_int4")
		RequestIpl("hei_Carrier_int5")
		RequestIpl("hei_Carrier_int6")
		RequestIpl("hei_carrier_lodlights")
		RequestIpl("hei_carrier_slod") ]]--
	-- Heist Yatch: -2043.974,-1031.582, 11.981
		RequestIpl("hei_yacht_heist")
		RequestIpl("hei_yacht_heist_enginrm")
		RequestIpl("hei_yacht_heist_lounge")
		RequestIpl("hei_yacht_heist_bridge")
		RequestIpl("hei_yacht_heist_bar")
		RequestIpl("hei_yacht_heist_bedrm")
		RequestIpl("hei_yacht_heist_distantlights")
		RequestIpl("hei_yacht_heist_lodlights")
	-- Bunkers - Exteriors
		RequestIpl("gr_case0_bunkerclosed")
		RequestIpl("gr_case1_bunkerclosed")
		RequestIpl("gr_case2_bunkerclosed")
		RequestIpl("gr_case3_bunkerclosed")
		RequestIpl("gr_case4_bunkerclosed")
		RequestIpl("gr_case5_bunkerclosed")
		RequestIpl("gr_case6_bunkerclosed")
		RequestIpl("gr_case7_bunkerclosed")
		RequestIpl("gr_case9_bunkerclosed")
		RequestIpl("gr_case10_bunkerclosed")
		RequestIpl("gr_case11_bunkerclosed")
	-- Bunkers - Interior: 892.63, -3245.86, -98.26
		RequestIpl("gr_entrance_placement")
		RequestIpl("gr_grdlc_int_01")
		RequestIpl("gr_grdlc_int_02")
		RequestIpl("gr_prop_gr_bunkerdoor")
		RequestIpl("gr_grdlc_interior_placement")
		RequestIpl("gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_")
		RequestIpl("gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_")
	-- Bahama Mamas: -1388.1, -618.41, 30.81
		RequestIpl("hei_sm_16_interior_v_bahama_milo_")
	-- Red Carpet Cinema: 300.5927, 199.7589, 104.3776
		--RequestIpl("redCarpet")
	-- UFO
		-- Zancudo: 	-2051.99, 3237.05, 1456.97
			-- RequestIpl("ufo")
		-- Hippie base: 2490.47, 3774.84, 2414.03
			-- RequestIpl("ufo_eye")
		-- Chiliad: 	501.52, 5593.86, 796.23
			-- RequestIpl("ufo_lod")
	-- North Yankton: 3217.69, -4834.82, 111.81
		--[[ RequestIpl("prologue01")
		RequestIpl("prologue01c")
		RequestIpl("prologue01d")
		RequestIpl("prologue01e")
		RequestIpl("prologue01f")
		RequestIpl("prologue01g")
		RequestIpl("prologue01h")
		RequestIpl("prologue01i")
		RequestIpl("prologue01j")
		RequestIpl("prologue01k")
		RequestIpl("prologue01z")
		RequestIpl("prologue02")
		RequestIpl("prologue03")
		RequestIpl("prologue03b")
		RequestIpl("prologue04")
		RequestIpl("prologue04b")
		RequestIpl("prologue05")
		RequestIpl("prologue05b")
		RequestIpl("prologue06")
		RequestIpl("prologue06b")
		RequestIpl("prologue06_int")
		RequestIpl("prologuerd")
		RequestIpl("prologuerdb ")
		RequestIpl("prologue_DistantLights")
		RequestIpl("prologue_LODLights")
		RequestIpl("prologue_m2_door") --]]
	-- CEO Offices :
		-- Arcadius Business Centre -140.5, -630.5, 157.5
			-- RequestIpl("ex_dt1_02_office_02b")	-- Executive Rich
			-- RequestIpl("ex_dt1_02_office_02c")	-- Executive Cool
			-- RequestIpl("ex_dt1_02_office_02a")	-- Executive Contrast
			-- RequestIpl("ex_dt1_02_office_01a")	-- Old Spice Warm
			-- RequestIpl("ex_dt1_02_office_01b")	-- Old Spice Classical
			-- RequestIpl("ex_dt1_02_office_01c")	-- Old Spice Vintage
			-- RequestIpl("ex_dt1_02_office_03a")	-- Power Broker Ice
			-- RequestIpl("ex_dt1_02_office_03b")	-- Power Broker Conservative
			RequestIpl("ex_dt1_02_office_03c")	-- Power Broker Polished
		-- Maze Bank Building -60.5, -800.5, 240.5
			-- RequestIpl("ex_dt1_11_office_02b")	-- Executive Rich
			-- RequestIpl("ex_dt1_11_office_02c")	-- Executive Cool
			-- RequestIpl("ex_dt1_11_office_02a")	-- Executive Contrast
			-- RequestIpl("ex_dt1_11_office_01a")	-- Old Spice Warm
			-- RequestIpl("ex_dt1_11_office_01b")	-- Old Spice Classical
			-- RequestIpl("ex_dt1_11_office_01c")	-- Old Spice Vintage
			-- RequestIpl("ex_dt1_11_office_03a")	-- Power Broker Ice
			-- RequestIpl("ex_dt1_11_office_03b")	-- Power Broker Conservative
			-- RequestIpl("ex_dt1_11_office_03c")	-- Power Broker Polished
		-- Lom Bank -1570.5, -573.5, 108.5
			-- RequestIpl("ex_sm_13_office_02b")	-- Executive Rich
			-- RequestIpl("ex_sm_13_office_02c")	-- Executive Cool
			-- RequestIpl("ex_sm_13_office_02a")	-- Executive Contrast
			RequestIpl("ex_sm_13_office_01a")	-- Old Spice Warm
			-- RequestIpl("ex_sm_13_office_01b")	-- Old Spice Classical
			-- RequestIpl("ex_sm_13_office_01c")	-- Old Spice Vintage
			-- RequestIpl("ex_sm_13_office_03a")	-- Power Broker Ice
			-- RequestIpl("ex_sm_13_office_03b")	-- Power Broker Conservative
			-- RequestIpl("ex_sm_13_office_03c")	-- Power Broker Polished
		-- Maze Bank West 1380,5 -480,5 60,5
			-- RequestIpl("ex_sm_15_office_02b")	-- Executive Rich
			-- RequestIpl("ex_sm_15_office_02c")	-- Executive Cool
			-- RequestIpl("ex_sm_15_office_02a")	-- Executive Contrast
			-- RequestIpl("ex_sm_15_office_01a")	-- Old Spice Warm
			-- RequestIpl("ex_sm_15_office_01b")	-- Old Spice Classical
			-- RequestIpl("ex_sm_15_office_01c")	-- Old Spice Vintage
			-- RequestIpl("ex_sm_15_office_03a")	-- Power Broker Ice
			-- RequestIpl("ex_sm_15_office_03b")	-- Power Broker Convservative
			-- RequestIpl("ex_sm_15_office_03c")	-- Power Broker Polished
		-- WareHouse 1020,5, 3100.5, -40
			-- RequestIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo ")
			-- RequestIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo ")
			-- RequestIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo ")
	-- Biker 1102, -3156, -37
		-- RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware02_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware03_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware04_milo")
		-- RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware05_milo")
	
	-- HANGAR -1266, -3014, -50
	-- RequestIpl("sm_smugdlc_interior_placement_interior_0_smugdlc_int_01_milo_")
	-- RequestIpl("sm_smugdlc_interior_placement")

    -- FACILTY + IAA + SUBMARINE
    --[[ RequestIpl("xm_x17dlc_int_placement")
    RequestIpl("xm_x17dlc_int_placement_0")
    RequestIpl("xm_x17dlc_int_placement_1")
    RequestIpl("xm_x17dlc_int_placement_strm_0")
    -- 2047, 2942, -62
    RequestIpl("xm_x17dlc_int_placement_interior_0_x17dlc_int_base_ent_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_1_x17dlc_int_base_loop_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_2_x17dlc_int_bse_tun_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_3_x17dlc_int_base_milo_")
    -- 550.5, 4800.5, -100
    RequestIpl("xm_x17dlc_int_placement_interior_4_x17dlc_int_facility_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_5_x17dlc_int_facility2_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_6_x17dlc_int_silo_01_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_7_x17dlc_int_silo_02_milo_")
    -- 550.5, 4800.5, -100
    RequestIpl("xm_x17dlc_int_placement_interior_8_x17dlc_int_sub_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_9_x17dlc_int_01_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_10_x17dlc_int_tun_straight_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_11_x17dlc_int_tun_slope_flat_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_12_x17dlc_int_tun_flat_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_13_x17dlc_int_tun_30d_r_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_14_x17dlc_int_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_15_x17dlc_int_straight_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_16_x17dlc_int_straight_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_17_x17dlc_int_tun_slope_flat_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_18_x17dlc_int_tun_slope_flat_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_19_x17dlc_int_base_flat_slope_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_20_x17dlc_int_base_flat_slope_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_21_x17dlc_int_tun_30d_r_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_22_x17dlc_int_tun_30d_r_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_23_x17dlc_int_tun_30d_r_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_24_x17dlc_int_tun_30d_r_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_25_x17dlc_int_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_26_x17dlc_int_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_27_x17dlc_int_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_28_x17dlc_int_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_29_x17dlc_tun_30d_l_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_30_v_apart_midspaz_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_31_v_studio_lo_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_32_v_garagem_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_33_x17dlc_int_02_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_34_x17dlc_int_lab_milo_")
    RequestIpl("xm_x17dlc_int_placement_interior_35_x17dlc_int_tun_entry_milo_")
    ]]--

	-- IMPORT/EXPORT -50.5, 800,5 210,5
		-- RequestIpl("imp_dt1_02_modgarage")
		-- RequestIpl("imp_dt1_02_cargarage_a")
		-- RequestIpl("imp_dt1_02_cargarage_b")
		-- RequestIpl("imp_dt1_02_cargarage_c")
		-- RequestIpl("imp_dt1_11_modgarage")
		-- RequestIpl("imp_dt1_11_cargarage_a")
		-- RequestIpl("imp_dt1_11_cargarage_b")
		-- RequestIpl("imp_dt1_11_cargarage_c")
	    -- -1600.5, 550.5, 75.5
		-- RequestIpl("imp_sm_13_modgarage")
		-- RequestIpl("imp_sm_13_cargarage_a")
		-- RequestIpl("imp_sm_13_cargarage_b")
		-- RequestIpl("imp_sm_13_cargarage_c")
		-- RequestIpl("imp_sm_15_modgarage")
		-- RequestIpl("imp_sm_15_cargarage_a")
		-- RequestIpl("imp_sm_15_cargarage_b")
		-- RequestIpl("imp_sm_15_cargarage_c")
		-- 1000.5, -3000.5, -500
		-- RequestIpl("imp_impexp_interior_placement")
		-- RequestIpl("imp_impexp_interior_placement_interior_0_impexp_int_01_milo_")
		-- RequestIpl("imp_impexp_interior_placement_interior_3_impexp_int_02_milo_")
		-- RequestIpl("imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_")
		-- RequestIpl("imp_impexp_interior_placement_interior_2_imptexp_mod_int_01_milo_")
	-- CS1 ?
		RemoveIpl("CS1_02_cf_offmission")
		RequestIpl("CS1_02_cf_onmission1")
		RequestIpl("CS1_02_cf_onmission2")
		RequestIpl("CS1_02_cf_onmission3")
		RequestIpl("CS1_02_cf_onmission4")
	-- MP APPARTEMENTS
		RequestIpl("apa_v_mp_h_01_a")
		RequestIpl("apa_v_mp_h_01_c")
		RequestIpl("apa_v_mp_h_01_b")
		RequestIpl("apa_v_mp_h_02_a")
		RequestIpl("apa_v_mp_h_02_c")
		RequestIpl("apa_v_mp_h_02_b")
		RequestIpl("apa_v_mp_h_03_a")
		RequestIpl("apa_v_mp_h_03_c")
		RequestIpl("apa_v_mp_h_03_b")
		RequestIpl("apa_v_mp_h_04_a")
		RequestIpl("apa_v_mp_h_04_c")
		RequestIpl("apa_v_mp_h_04_b")
		RequestIpl("apa_v_mp_h_05_a")
		RequestIpl("apa_v_mp_h_05_c")
		RequestIpl("apa_v_mp_h_05_b")
		RequestIpl("apa_v_mp_h_06_a")
		RequestIpl("apa_v_mp_h_06_c")
		RequestIpl("apa_v_mp_h_06_b")
		RequestIpl("apa_v_mp_h_07_a")
		RequestIpl("apa_v_mp_h_07_c")
		RequestIpl("apa_v_mp_h_07_b")
		RequestIpl("apa_v_mp_h_08_a")
		RequestIpl("apa_v_mp_h_08_c")
		RequestIpl("apa_v_mp_h_08_b")
	-- OUTSIDE APPARTEMENTS
		RequestIpl("apa_ss1_02_building01")
		RequestIpl("apa_ss1_11_flats")
		RequestIpl("apa_ch2_05e_res5")
		RequestIpl("apa_ch2_05e_res5_LOD")
		RequestIpl("apa_ch2_09c_hs07")
		RequestIpl("apa_ch2_09c_build_11_07_LOD")
	-- LEV
		RequestIpl("v_ilev_bs_door")
		RequestIpl("v_ilev_hd_door_l")
		RequestIpl("v_ilev_hd_door_r")
		RequestIpl("v_ilev_cs_door01")
		RequestIpl("v_ilev_cs_door01_r")
		RequestIpl("v_ilev_clothmiddoor")
		RequestIpl("v_ilev_ch_glassdoor")
		RequestIpl("v_ilev_ta_door")
		RequestIpl("v_ilev_mm_doorm_l")
		RequestIpl("v_ilev_mm_doorm_r")
		RequestIpl("v_ilev_mm_windowwc")
		RequestIpl("v_ilev_fa_frontdoor")
		RequestIpl("v_ilev_fh_frntdoor")
		RequestIpl("v_ilev_trev_doorfront")
		RequestIpl("v_ilev_fh_frontdoor")
		RequestIpl("v_ilev_trevtraildr")
		RequestIpl("v_ilev_carmod3door")
		RequestIpl("v_ilev_janitor_frontdoor")
		RequestIpl("v_ilev_ss_door8")
		RequestIpl("v_ilev_ss_door7")
		RequestIpl("v_ilev_ss_door02")
		RequestIpl("v_ilev_ss_door03")
		RequestIpl("v_ilev_store_door")
		RequestIpl("v_ilev_ss_door04")
		RequestIpl("v_ilev_bank4door02")
		RequestIpl("v_ilev_bank4door01")
		RequestIpl("v_ilev_lester_doorfront")
		RequestIpl("v_ilev_lester_doorveranda")
		RequestIpl("v_ilev_deviantfrontdoor")
		RequestIpl("v_ilev_cs_door")
		RequestIpl("v_ilev_gangsafedoor")
		RequestIpl("v_ilev_ra_door1_l")
		RequestIpl("v_ilev_ra_door1_r")
		RequestIpl("v_ilev_fib_door1")
		RequestIpl("v_ilev_tort_door")
		RequestIpl("v_ilev_bl_shutter2")
		RequestIpl("v_ilev_rc_door3_l")
		RequestIpl("v_ilev_rc_door3_r")
		RequestIpl("v_ilev_csr_door_l")
		RequestIpl("v_ilev_csr_door_r")
		RequestIpl("v_ilev_abbmaindoor")
		RequestIpl("v_ilev_abbmaindoor2")
		RequestIpl("v_ilev_door_orangesolid")
		RequestIpl("v_ilev_housedoor1")
		RequestIpl("v_ilev_fb_doorshortl")
		RequestIpl("v_ilev_fb_doorshortr")
		RequestIpl("v_ilev_fb_door01")
		RequestIpl("v_ilev_fb_door02")
		RequestIpl("v_ilev_gtdoor")
		RequestIpl("v_ilev_po_door")
		RequestIpl("v_ilev_fibl_door02")
		RequestIpl("v_ilev_fibl_door01")
		RequestIpl("v_ilev_ct_door01")
		RequestIpl("v_ilev_genbankdoor2")
		RequestIpl("v_ilev_genbankdoor1")
		RequestIpl("v_ilev_roc_door4")
		RequestIpl("v_ilev_bk_door")
		RequestIpl("v_ilev_shrf2door")
		RequestIpl("v_ilev_shrfdoor")
		RequestIpl("v_ilev_gc_door04")
		RequestIpl("v_ilev_gc_door03")
		RequestIpl("v_ilev_gc_door01")
		RequestIpl("v_ilev_bl_doorel_l")
		RequestIpl("v_ilev_bl_doorel_r")
		RequestIpl("v_ilev_cbankcountdoor01")
	-- PROPS
		RequestIpl("prop_ld_garaged_01")
		RequestIpl("prop_bh1_48_backdoor_l")
		RequestIpl("prop_bh1_48_backdoor_r")
		RequestIpl("prop_bh1_48_gate_1")
		RequestIpl("prop_sc1_21_g_door_01")
		RequestIpl("prop_cs4_10_tr_gd_01")
		RequestIpl("prop_com_ls_door_01")
		RequestIpl("prop_id2_11_gdoor")
		RequestIpl("prop_ron_door_01")
		RequestIpl("prop_com_gar_door_01")
		RequestIpl("prop_strip_door_01")
		RequestIpl("prop_magenta_door")
		RequestIpl("prop_motel_door_09")
		RequestIpl("prop_cs6_03_door_l")
		RequestIpl("prop_cs6_03_door_r")
		RequestIpl("prop_gar_door_01")
		RequestIpl("prop_gar_door_02")
		RequestIpl("prop_map_door_01")
		RequestIpl("prop_epsilon_door_l")
		RequestIpl("prop_epsilon_door_r")
		RequestIpl("prop_ch2_09c_garage_door")
		RequestIpl("prop_cs4_05_tdoor")
		RequestIpl("prop_ss1_10_door_l")
		RequestIpl("prop_ss1_10_door_r")
		RequestIpl("prop_damdoor_01")
		RequestIpl("prop_bhhotel_door_l")
		RequestIpl("prop_bhhotel_door_r")
		RequestIpl("prop_ch3_04_door_01l")
		RequestIpl("prop_ch3_04_door_01r")
		RequestIpl("prop_ch3_01_trlrdoor_l")
		RequestIpl("prop_ch3_01_trlrdoor_r")
		RequestIpl("prop_lrggate_01c_l")
		RequestIpl("prop_lrggate_01c_r")
		RequestIpl("prop_ch3_04_door_02")
		RequestIpl("prop_ch1_07_door_01l")
		RequestIpl("prop_ch1_07_door_01r")
		RequestIpl("prop_gar_door_04")
		RequestIpl("prop_gate_tep_01_l")
		RequestIpl("prop_gate_tep_01_r")
		RequestIpl("prop_artgallery_02_dr")
		RequestIpl("prop_artgallery_02_dl")
		RequestIpl("prop_fnclink_07gate1")
		RequestIpl("prop_abat_slide")
		
	-- TO SORT
RequestIpl("chop_props")
RequestIpl("v_rockclub")
RemoveIpl("v_carshowroom")
RemoveIpl("shutter_open")
RemoveIpl("shutter_closed")
RemoveIpl("shr_int")
RemoveIpl("csr_inMission")
RequestIpl("v_carshowroom")
RequestIpl("shr_int")
RequestIpl("shutter_closed")
RequestIpl("railing_start")
RemoveIpl("sp1_10_fake_interior")
RemoveIpl("sp1_10_fake_interior_lod")
RequestIpl("sp1_10_real_interior")
RequestIpl("sp1_10_real_interior_lod")
RemoveIpl("id2_14_during_door")
RemoveIpl("id2_14_during1")
RemoveIpl("id2_14_during2")
RemoveIpl("id2_14_on_fire")
RemoveIpl("id2_14_post_no_int")
RemoveIpl("id2_14_pre_no_int")
RemoveIpl("id2_14_during_door")
RequestIpl("id2_14_during1")
RequestIpl("coronertrash")
RequestIpl("Coroner_Int_on")
RemoveIpl("Coroner_Int_off")
RemoveIpl("bh1_16_refurb")
RemoveIpl("bh1_16_doors_shut")
RequestIpl("refit_unload")
RequestIpl("post_hiest_unload")
RequestIpl("Carwash_with_spinners")
RequestIpl("ferris_finale_Anim")
RemoveIpl("ch1_02_closed")
RequestIpl("ch1_02_open")
RequestIpl("AP1_04_TriAf01")
RequestIpl("CS2_06_TriAf02")
RequestIpl("CS4_04_TriAf03")
RemoveIpl("scafstartimap")
RequestIpl("scafendimap")
RemoveIpl("DT1_05_HC_REMOVE")
RequestIpl("DT1_05_HC_REQ")
RequestIpl("DT1_05_REQUEST")
RemoveIpl("DT1_03_Shutter")
RemoveIpl("DT1_03_Gr_Closed")
RequestIpl("ss1_11_ss1_emissive_a")
RequestIpl("ss1_11_detail01b")
RequestIpl("ss1_11_Flats_LOD")
RequestIpl("SS1_02_Building01_LOD")
RequestIpl("SS1_LOD_01_02_08_09_10_11")
RequestIpl("SS1_02_SLOD1")
RequestIpl("SS1_Emissive_SS1_02a_LOD")
RequestIpl("ss1_02_ss1_emissive_ss1_02")
RequestIpl("hei_dt1_03_build1x")
RequestIpl("DT1_Emissive_DT1_03_b1")
RequestIpl("dt1_03_dt1_Emissive_b1")
RequestIpl("ch2_09c_build_11_07_LOD")
RequestIpl("CH2_09c_Emissive_07_LOD")
RequestIpl("ch2_09c_hs07_details")
RequestIpl("CH2_09c_Emissive_07")
RequestIpl("dt1_11_dt1_emissive_dt1_11")
RequestIpl("dt1_11_dt1_tower")
RequestIpl("ap1_02_door_l")
RequestIpl("ap1_02_door_r")
RequestIpl("p_cut_door_03")
RequestIpl("p_cut_door_02")
RequestIpl("p_jewel_door_l")
RequestIpl("p_jewel_door_r1")
RequestIpl("prop_fnclink_03gate5")
RemoveIpl("facelobbyfake")
RemoveIpl("fakeint")
RequestIpl("vb_30_crimetape")
RequestIpl("sheriff_cap")
RequestIpl("v_sheriff2")
RemoveIpl("CS1_16_sheriff_cap")
RequestIpl("chemgrill_grp1")
RequestIpl("DT1_03_Shutter")
RequestIpl("ch1_02_closed")
RequestIpl("facelobby")
RequestIpl("shr_int")
RequestIpl("post_hiest_unload")
RequestIpl("burnt_switch_off")
RequestIpl("ch1_02_open")
RequestIpl("lr_cs6_08_grave_closed")
RequestIpl("bkr_bi_id1_23_door")
RequestIpl("Apa_V_mp_h_0%d_A")
RequestIpl("lower_walls_default")
RequestIpl("Furnishings_02")
RequestIpl("Walls_02")
RequestIpl("Decorative_02")
RequestIpl("Mural_02")
RequestIpl("Furnishings_01")
RequestIpl("Walls_01")
RequestIpl("Decorative_01")
RequestIpl("Mural_01")
RequestIpl("V_57_FranklinStuff")
RequestIpl("swap_clean_apt")
RequestIpl("layer_whiskey")
RequestIpl("layer_sextoys_a")
RequestIpl("swap_mrJam_A")
RequestIpl("swap_sofa_A")
RequestIpl("V_Michael_bed_tidy")
RequestIpl("V_Michael_L_Items")
RequestIpl("V_Michael_S_Items")
RequestIpl("V_Michael_D_Items")
RequestIpl("V_Michael_M_Items")
RequestIpl("Michael_premier")
RequestIpl("V_Michael_plane_ticket")
RequestIpl("showhome_only")
RequestIpl("franklin_settled")
RequestIpl("franklin_unpacking")
RequestIpl("bong_and_wine")
RequestIpl("facelobby")
RemoveIpl("smboat")
RequestIpl("cargoship")
RemoveIpl("sp1_10_fake_interior")
RequestIpl("sp1_10_real_interior")
RequestIpl("Coroner_Int_on")
RequestIpl("post_hiest_unload")
RequestIpl("Carwash_with_spinners")
RequestIpl("ferris_finale_Anim")
RemoveIpl("ch1_02_closed")
RequestIpl("ch1_02_open")
RequestIpl("AP1_04_TriAf01")
RequestIpl("CS2_06_TriAf02")
RequestIpl("CS4_04_TriAf03")
RemoveIpl("scafstartimap")
RequestIpl("scafendimap")
RemoveIpl("DT1_05_HC_REMOVE")
RequestIpl("DT1_05_HC_REQ")
RequestIpl("DT1_05_REQUEST")
RemoveIpl("DT1_03_Shutter")
RemoveIpl("DT1_03_Gr_Closed")
RemoveIpl("hei_bi_hw1_13_door")
RemoveIpl("trailerparkA_grp1")
RemoveIpl("trailerparkA_grp2")
RemoveIpl("occl_trailerA_grp1")
RemoveIpl("trailerparkB_grp1")
RemoveIpl("trailerparkB_grp2")
RemoveIpl("occl_trailerB_grp1")
RemoveIpl("trailerparkC_grp1")
RemoveIpl("trailerparkC_grp2")
RemoveIpl("occl_trailerC_grp1")
RemoveIpl("trailerparkD_grp1")
RemoveIpl("trailerparkD_grp2")
RemoveIpl("occl_trailerD_grp1")
RemoveIpl("trailerparkE_grp1")
RemoveIpl("trailerparkE_grp2")
RemoveIpl("occl_trailerE_grp1")
RemoveIpl("des_methtrailer")
RemoveIpl("methtrailer_grp1")
RemoveIpl("methtrailer_grp2")
RemoveIpl("methtrailer_grp3")
RemoveIpl("occl_meth_grp1")
RemoveIpl("occl_meth_grp1")
RequestIpl("trailerparkA_grp1")
RequestIpl("occl_trailerA_grp1")
RequestIpl("trailerparkB_grp1")
RequestIpl("occl_trailerB_grp1")
RequestIpl("trailerparkC_grp1")
RequestIpl("occl_trailerC_grp1")
RequestIpl("trailerparkD_grp1")
RequestIpl("occl_trailerD_grp1")
RequestIpl("trailerparkE_grp1")
RequestIpl("occl_trailerE_grp1")
RequestIpl("occl_meth_grp1")
RequestIpl("methtrailer_grp1")
RemoveIpl("v_carshowroom")
RemoveIpl("shutter_open")
RemoveIpl("shutter_closed")
RemoveIpl("shr_int")
RemoveIpl("csr_inMission")
RequestIpl("v_carshowroom")
RequestIpl("shutter_closed")
RemoveIpl("Coroner_Int_off")
RequestIpl("coronertrash")
RequestIpl("Coroner_Int_on")
RemoveIpl("id2_14_during_door")
RemoveIpl("id2_14_during1")
RemoveIpl("id2_14_during2")
RemoveIpl("id2_14_on_fire")
RemoveIpl("id2_14_post_no_int")
RemoveIpl("id2_14_pre_no_int")
RemoveIpl("id2_14_during_door")
RequestIpl("id2_14_during1")
RequestIpl("facelobby")
RemoveIpl("sp1_10_fake_interior")
RemoveIpl("sp1_10_fake_interior_lod")
RequestIpl("sp1_10_real_interior")
RequestIpl("sp1_10_real_interior_lod")
RemoveIpl("ch1_02_closed")
RequestIpl("ch1_02_open")
RequestIpl("cargoship")
RequestIpl("railing_start")
RemoveIpl("bh1_16_refurb")
RemoveIpl("jewel2fake")
RemoveIpl("bh1_16_doors_shut")
RequestIpl("ferris_finale_Anim")
RequestIpl("AP1_04_TriAf01")
RequestIpl("CS2_06_TriAf02")
RequestIpl("CS4_04_TriAf03")
RemoveIpl("scafstartimap")
RequestIpl("scafendimap")
RemoveIpl("DT1_05_HC_REMOVE")
RequestIpl("DT1_05_HC_REQ")
RequestIpl("DT1_05_REQUEST")
RemoveIpl("DT1_03_Shutter")
RemoveIpl("DT1_03_Gr_Closed")
end)
