var tableauQuestion = [
    {   question : "Que veut dire «RP» ?",
        propositionA : "Rond-point.",
        propositionB : "Role-play.",
        propositionC : "Relation publique.",
        propositionD : "Regle prioritaire.",
        reponse : "B"},
    {   question : "Qu'est-ce que le principe du «RP» ?",
        propositionA : "Les participants adoptent le rôle d'un personnage qui peut avoir une personnalité, des motivations, des origines...",
        propositionB : "C'est un carrefour où aboutissent plusieurs routes.",
        propositionC : "le RP est l'ensemble des méthodes et techniques de communication utilisées par les sociétés ou les groupements d'intérêt pour informer à une échelle interne mais surtout externe.",
        reponse : "A"},
    {   question : "Qu'est-ce que le Metagame ? (Interdit)",
        propositionA : "Le metagame est le fait d'utiliser des informations RP en OOC.",
        propositionB : "Le metagame est le fait de mélanger ce qui est RP(IC) et ce qui ne l'est pas (OOC).",
        reponse : "B"},
    {   question : "Qu'est-ce que le Deathmatch ? (Interdit)",
        propositionA : "C'est une partie à mort par équipe.",
        propositionB : "C'est le fait de tuer quelqu'un sans raison ou sans bonne raison RP.",
        reponse : "B"},
    {   question : "Qu'est-ce que le In Character (IC) ?",
        propositionA : "Quand vous incarnez votre personnage, vous vous mettez dans sa peau et agissez comme vous pensez qu'il le ferait dans la vie réelle.",
        propositionB : "C'est nous même hors de notre personnage.",
        reponse : "A"},
    {   question : "Qu'est-ce que le Out Of Character (OOC) ?",
        propositionA : "Quand vous incarnez votre personnage, vous vous mettez dans sa peau et agissez comme vous pensez qu'il le ferait dans la vie réelle.",
        propositionB : "C'est nous même hors de notre personnage (Hors Roleplay).",
        reponse : "B"},
    {   question : "Qu'est-ce que le revenge kill (RK) ?",
        propositionA : "C'est le fait de se venger de quelqu'un dont on se souvient.",
        propositionB : "C'est le fait de se venger de quelqu'un qui nous a tué précédemment (Interdit).",
        reponse : "B"},
    {   question : "Qu'est-ce que le powergaming ? (Interdit)",
        propositionA : "Le fait d'agir no-RP, comme par exemple sauter d'une falaise en voiture et continuer à rouler tranquillement, dans la vie réelle votre voiture serait complètement détruite.",
        propositionB : "C'est le d'abuser de ses pouvoirs.",
        reponse : "A"},
    {   question : "Qu'est-ce que le carkill ?",
        propositionA : "C'est le fait d'écraser une personne en ayant pour but de tuer (Interdit).",
        propositionB : "C'est le fait de tuer un véhicule.",
        propositionC : "C'est le fait de percuter sans pour autant le tuer.",
        reponse : "A"},
    {   question : "Vous êtes en plein milieu d'une fusillade, que faites-vous ?",
        propositionA : "Je sort mon pistolet et je participe.",
        propositionB : "Je me cache et j'appel les urgences.",
        reponse : "B"},
    {   question : "Un agent de police vous demande de vous mettre sur le cote de la route puis de sortir de votre véhicule. Vous voyez son collègue vous observer attentivement en cas de fuite. Dans cette situation que faites-vous ?",
        propositionA : "J'écrase l'agent de police.",
        propositionB : "Je sors du véhicule puis je sors une kalash afin de tuer les deux agents.",
        propositionC : "Je respecte les demandes de l'agent et je répond à ses questions.",
        propositionD : "Je rigole et bois une bière avec eux.",
        reponse : "C"},

]
